# -*- coding: utf-8 -*-
"""LCTES2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDMr_32sLXGPh9zRMyl_UcVJNM9R2BOZ

# Environment setup
"""

import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import figure

WORKSPACE_DIR = "/workspace"
RESULTS_DIR = os.path.join(WORKSPACE_DIR, "results")

def gen_op_counts_qconv(n, h, w, o, kh, kw, c, residual=False):
    dotp = n * h * w * o * kh * kw * c
    rcnv = n * h * w * o
    rrsd = (n * h * w * o) if residual else 0
    return dotp + rcnv + rrsd

def gen_mem_counts_qconv(n, h, w, o, kh, kw, c, ih, iw, residual=False, per_channel=True):
    image = n * ih * iw * c
    kernel = o * kh * kw * c
    if c > 64:
      kernel *= (ih + 13) // 14
      kernel *= (iw + 13) // 14

    bias = o
    requant = 1
    if per_channel:
      requant = o
    if residual:
      requant += 1
    residual = (n * h * w * o) if residual else 0
    output = n * h * w * o
    return image + kernel + bias + requant + residual + output

# matplotlib.rcParams.update({'font.size': 14})
matplotlib.rcParams.update({'font.size': 8})

"""# Theoretical behaviour of each model"""

def gen_lenet5_op_counts(n):
    return [
        gen_op_counts_qconv(n, 28, 28, 6, 5, 5, 1),
        gen_op_counts_qconv(n, 10, 10, 16, 5, 5, 6),
        gen_op_counts_qconv(n, 1, 1, 120, 1, 1, 16 * 5 * 5),
        gen_op_counts_qconv(n, 1, 1, 84, 1, 1, 120),
        gen_op_counts_qconv(n, 1, 1, 10, 1, 1, 84),
    ]

def gen_lenet5_mem_counts(n):
    return [
        gen_mem_counts_qconv(n, 14, 14, 6, 5, 5, 1, 28, 28),
        gen_mem_counts_qconv(n, 5, 5, 16, 5, 5, 6, 14, 14),
        gen_mem_counts_qconv(n, 1, 1, 120, 1, 1, 16 * 5 * 5, 1, 1, per_channel=False),
        gen_mem_counts_qconv(n, 1, 1, 84, 1, 1, 120, 1, 1, per_channel=False),
        gen_mem_counts_qconv(n, 1, 1, 10, 1, 1, 84, 1, 1, per_channel=False),
    ]

def gen_vgg11_op_counts(n):
    return [
        gen_op_counts_qconv(n, 224, 224, 64, 3, 3, 3),
        gen_op_counts_qconv(n, 112, 112, 128, 3, 3, 64),
        gen_op_counts_qconv(n, 56, 56, 256, 3, 3, 128),
        gen_op_counts_qconv(n, 56, 56, 256, 3, 3, 256),
        gen_op_counts_qconv(n, 28, 28, 512, 3, 3, 256),
        gen_op_counts_qconv(n, 28, 28, 512, 3, 3, 512),
        gen_op_counts_qconv(n, 14, 14, 512, 3, 3, 512),
        gen_op_counts_qconv(n, 14, 14, 512, 3, 3, 512),
        gen_op_counts_qconv(n, 1, 1, 4096, 1, 1, 512 * 7 * 7),
        gen_op_counts_qconv(n, 1, 1, 4096, 1, 1, 4096),
        gen_op_counts_qconv(n, 1, 1, 1000, 1, 1, 4096),
    ]

def gen_vgg11_mem_counts(n):
    return [
        gen_mem_counts_qconv(n, 112, 112, 64, 3, 3, 3, 224, 224),
        gen_mem_counts_qconv(n, 56, 56, 128, 3, 3, 64, 112, 112),
        gen_mem_counts_qconv(n, 56, 56, 256, 3, 3, 128, 56, 56),
        gen_mem_counts_qconv(n, 28, 28, 256, 3, 3, 256, 56, 56),
        gen_mem_counts_qconv(n, 28, 28, 512, 3, 3, 256, 28, 28),
        gen_mem_counts_qconv(n, 14, 14, 512, 3, 3, 512, 28, 28),
        gen_mem_counts_qconv(n, 14, 14, 512, 3, 3, 512, 14, 14),
        gen_mem_counts_qconv(n, 7, 7, 512, 3, 3, 512, 14, 14),
        gen_mem_counts_qconv(n, 1, 1, 4096, 1, 1, 512 * 7 * 7, 1, 1, per_channel=False),
        gen_mem_counts_qconv(n, 1, 1, 4096, 1, 1, 4096, 1, 1, per_channel=False),
        gen_mem_counts_qconv(n, 1, 1, 1000, 1, 1, 4096, 1, 1, per_channel=False),
    ]


def gen_vgg16_op_counts(n):
    return [
        gen_op_counts_qconv(n, 224, 224, 64, 3, 3, 3),
        gen_op_counts_qconv(n, 224, 224, 64, 3, 3, 64),

        gen_op_counts_qconv(n, 112, 112, 128, 3, 3, 64),
        gen_op_counts_qconv(n, 112, 112, 128, 3, 3, 128),

        gen_op_counts_qconv(n, 56, 56, 256, 3, 3, 128),
        gen_op_counts_qconv(n, 56, 56, 256, 3, 3, 256),
        gen_op_counts_qconv(n, 56, 56, 256, 3, 3, 256),

        gen_op_counts_qconv(n, 28, 28, 512, 3, 3, 256),
        gen_op_counts_qconv(n, 28, 28, 512, 3, 3, 512),
        gen_op_counts_qconv(n, 28, 28, 512, 3, 3, 512),

        gen_op_counts_qconv(n, 14, 14, 512, 3, 3, 512),
        gen_op_counts_qconv(n, 14, 14, 512, 3, 3, 512),
        gen_op_counts_qconv(n, 14, 14, 512, 3, 3, 512),

        gen_op_counts_qconv(n, 1, 1, 4096, 1, 1, 512 * 7 * 7),
        gen_op_counts_qconv(n, 1, 1, 4096, 1, 1, 4096),
        gen_op_counts_qconv(n, 1, 1, 1000, 1, 1, 4096),
    ]

def gen_vgg16_mem_counts(n):
    return [
        gen_mem_counts_qconv(n, 224, 224, 64, 3, 3, 3, 224, 224),
        gen_mem_counts_qconv(n, 112, 112, 64, 3, 3, 64, 224, 224),

        gen_mem_counts_qconv(n, 112, 112, 128, 3, 3, 64, 112, 112),
        gen_mem_counts_qconv(n, 56, 56, 128, 3, 3, 128, 112, 112),

        gen_mem_counts_qconv(n, 56, 56, 256, 3, 3, 128, 56, 56),
        gen_mem_counts_qconv(n, 56, 56, 256, 3, 3, 256, 56, 56),
        gen_mem_counts_qconv(n, 28, 28, 256, 3, 3, 256, 56, 56),

        gen_mem_counts_qconv(n, 28, 28, 512, 3, 3, 256, 28, 28),
        gen_mem_counts_qconv(n, 28, 28, 512, 3, 3, 512, 28, 28),
        gen_mem_counts_qconv(n, 14, 14, 512, 3, 3, 512, 28, 28),

        gen_mem_counts_qconv(n, 14, 14, 512, 3, 3, 512, 14, 14),
        gen_mem_counts_qconv(n, 14, 14, 512, 3, 3, 512, 14, 14),
        gen_mem_counts_qconv(n, 7, 7, 512, 3, 3, 512, 14, 14),

        gen_mem_counts_qconv(n, 1, 1, 4096, 1, 1, 512 * 7 * 7, 1, 1, per_channel=False),
        gen_mem_counts_qconv(n, 1, 1, 4096, 1, 1, 4096, 1, 1, per_channel=False),
        gen_mem_counts_qconv(n, 1, 1, 1000, 1, 1, 4096, 1, 1, per_channel=False),
    ]

def gen_yolo_op_counts(n):
    return [
        gen_op_counts_qconv(n, 208 * 2, 208 * 2, 16, 3, 3, 3),
        gen_op_counts_qconv(n, 104 * 2, 104 * 2, 32, 3, 3, 16),
        gen_op_counts_qconv(n, 52 * 2, 52 * 2, 64, 3, 3, 32),
        gen_op_counts_qconv(n, 26 * 2, 26 * 2, 128, 3, 3, 64),
        gen_op_counts_qconv(n, 13 * 2, 13 * 2, 256, 3, 3, 128),
        gen_op_counts_qconv(n, 13, 13, 512, 3, 3, 256),
        gen_op_counts_qconv(n, 13, 13, 1024, 3, 3, 512),
        gen_op_counts_qconv(n, 13, 13, 1024, 3, 3, 1024),
        gen_op_counts_qconv(n, 13, 13, 125, 1, 1, 1024),
    ]

def gen_yolo_mem_counts(n):
    return [
        gen_mem_counts_qconv(n, 208, 208, 16, 3, 3, 3, 416, 416),
        gen_mem_counts_qconv(n, 104, 104, 32, 3, 3, 16, 208, 208),
        gen_mem_counts_qconv(n, 52, 52, 64, 3, 3, 32, 104, 104),
        gen_mem_counts_qconv(n, 26, 26, 128, 3, 3, 64, 52, 52),
        gen_mem_counts_qconv(n, 13, 13, 256, 3, 3, 128, 26, 26),
        gen_mem_counts_qconv(n, 13, 13, 512, 3, 3, 256, 13, 13),
        gen_mem_counts_qconv(n, 13, 13, 1024, 3, 3, 512, 13, 13),
        gen_mem_counts_qconv(n, 13, 13, 1024, 3, 3, 1024, 13, 13),
        gen_mem_counts_qconv(n, 13, 13, 125, 1, 1, 1024, 13, 13),
    ]

def gen_resnet18_op_counts(n):
    return [
        gen_op_counts_qconv(n, 56, 56, 64, 3, 3, 64),
        gen_op_counts_qconv(n, 56, 56, 64, 3, 3, 64, residual=True),

        gen_op_counts_qconv(n, 56, 56, 64, 3, 3, 64),
        gen_op_counts_qconv(n, 56, 56, 64, 3, 3, 64, residual=True),

        gen_op_counts_qconv(n, 28, 28, 128, 3, 3, 64),
        gen_op_counts_qconv(n, 28, 28, 128, 1, 1, 64),
        gen_op_counts_qconv(n, 28, 28, 128, 3, 3, 128, residual=True),

        gen_op_counts_qconv(n, 28, 28, 128, 3, 3, 128),
        gen_op_counts_qconv(n, 28, 28, 128, 3, 3, 128, residual=True),

        gen_op_counts_qconv(n, 14, 14, 256, 3, 3, 128),
        gen_op_counts_qconv(n, 14, 14, 256, 1, 1, 128),
        gen_op_counts_qconv(n, 14, 14, 256, 3, 3, 256, residual=True),

        gen_op_counts_qconv(n, 14, 14, 256, 3, 3, 256),
        gen_op_counts_qconv(n, 14, 14, 256, 3, 3, 256, residual=True),

        gen_op_counts_qconv(n, 7, 7, 512, 3, 3, 256),
        gen_op_counts_qconv(n, 7, 7, 512, 1, 1, 256),
        gen_op_counts_qconv(n, 7, 7, 512, 3, 3, 512, residual=True),

        gen_op_counts_qconv(n, 7, 7, 512, 3, 3, 512),
        gen_op_counts_qconv(n, 7, 7, 512, 3, 3, 512, residual=True),

        gen_op_counts_qconv(n, 1, 1, 1000, 1, 1, 512, residual=False)
    ]

def gen_resnet18_mem_counts(n):
    return [
        gen_mem_counts_qconv(n, 56, 56, 64, 3, 3, 64, 56, 56),
        gen_mem_counts_qconv(n, 56, 56, 64, 3, 3, 64, 56, 56, residual=True),

        gen_mem_counts_qconv(n, 56, 56, 64, 3, 3, 64, 56, 56),
        gen_mem_counts_qconv(n, 56, 56, 64, 3, 3, 64, 56, 56, residual=True),

        gen_mem_counts_qconv(n, 28, 28, 128, 3, 3, 64, 56, 56),
        gen_mem_counts_qconv(n, 28, 28, 128, 1, 1, 64, 28, 28), # 1x1 /2 by offset
        gen_mem_counts_qconv(n, 28, 28, 128, 3, 3, 128, 28, 28, residual=True),

        gen_mem_counts_qconv(n, 28, 28, 128, 3, 3, 128, 28, 28),
        gen_mem_counts_qconv(n, 28, 28, 128, 3, 3, 128, 28, 28, residual=True),

        gen_mem_counts_qconv(n, 14, 14, 256, 3, 3, 128, 28, 28),
        gen_mem_counts_qconv(n, 14, 14, 256, 1, 1, 128, 14, 14), # 1x1 /2 by offset
        gen_mem_counts_qconv(n, 14, 14, 256, 3, 3, 256, 14, 14, residual=True),

        gen_mem_counts_qconv(n, 14, 14, 256, 3, 3, 256, 14, 14),
        gen_mem_counts_qconv(n, 14, 14, 256, 3, 3, 256, 14, 14, residual=True),

        gen_mem_counts_qconv(n, 7, 7, 512, 3, 3, 256, 14, 14),
        gen_mem_counts_qconv(n, 7, 7, 512, 1, 1, 256, 7, 7), # 1x1 /2 by offset
        gen_mem_counts_qconv(n, 7, 7, 512, 3, 3, 512, 7, 7, residual=True),

        gen_mem_counts_qconv(n, 7, 7, 512, 3, 3, 512, 7, 7),
        gen_mem_counts_qconv(n, 7, 7, 512, 3, 3, 512, 7, 7, residual=True),

        gen_mem_counts_qconv(n, 1, 1, 1000, 1, 1, 512, 1, 1, residual=False, per_channel=False)
    ]
def gen_resnet50_op_counts(n):
    return [
      gen_op_counts_qconv(1, 56, 56, 64, 1, 1, 64),
        gen_op_counts_qconv(1, 56, 56, 64, 3, 3, 64), # 1
        gen_op_counts_qconv(1, 56, 56, 256, 1, 1, 64),
        gen_op_counts_qconv(1, 56, 56, 256, 1, 1, 64, residual=True),
        gen_op_counts_qconv(1, 56, 56, 64, 1, 1, 256),
        gen_op_counts_qconv(1, 56, 56, 64, 3, 3, 64), # 5
        gen_op_counts_qconv(1, 56, 56, 256, 1, 1, 64, residual=True),
        gen_op_counts_qconv(1, 56, 56, 64, 1, 1, 256),
        gen_op_counts_qconv(1, 56, 56, 64, 3, 3, 64), # 8
        gen_op_counts_qconv(1, 56, 56, 256, 1, 1, 64, residual=True),
        gen_op_counts_qconv(1, 56, 56, 128, 1, 1, 256),
        gen_op_counts_qconv(1, 28, 28, 128, 3, 3, 128),
        gen_op_counts_qconv(1, 28, 28, 512, 1, 1, 256),
        gen_op_counts_qconv(1, 28, 28, 512, 1, 1, 128, residual=True),
        gen_op_counts_qconv(1, 28, 28, 128, 1, 1, 512),
        gen_op_counts_qconv(1, 28, 28, 128, 3, 3, 128), # 15
        gen_op_counts_qconv(1, 28, 28, 512, 1, 1, 128, residual=True),
        gen_op_counts_qconv(1, 28, 28, 128, 1, 1, 512),
        gen_op_counts_qconv(1, 28, 28, 128, 3, 3, 128), # 18
        gen_op_counts_qconv(1, 28, 28, 512, 1, 1, 128, residual=True),
        gen_op_counts_qconv(1, 28, 28, 128, 1, 1, 512),
        gen_op_counts_qconv(1, 28, 28, 128, 3, 3, 128), # 21
        gen_op_counts_qconv(1, 28, 28, 512, 1, 1, 128, residual=True),
        gen_op_counts_qconv(1, 28, 28, 256, 1, 1, 512),
        gen_op_counts_qconv(1, 14, 14, 256, 3, 3, 256),
        gen_op_counts_qconv(1, 14, 14, 1024, 1, 1, 512),
        gen_op_counts_qconv(1, 14, 14, 1024, 1, 1, 256, residual=True),
        gen_op_counts_qconv(1, 14, 14, 256, 1, 1, 1024),
        gen_op_counts_qconv(1, 14, 14, 256, 3, 3, 256), # 28
        gen_op_counts_qconv(1, 14, 14, 1024, 1, 1, 256, residual=True),
        gen_op_counts_qconv(1, 14, 14, 256, 1, 1, 1024),
        gen_op_counts_qconv(1, 14, 14, 256, 3, 3, 256), # 31
        gen_op_counts_qconv(1, 14, 14, 1024, 1, 1, 256, residual=True),
        gen_op_counts_qconv(1, 14, 14, 256, 1, 1, 1024),
        gen_op_counts_qconv(1, 14, 14, 256, 3, 3, 256), # 34
        gen_op_counts_qconv(1, 14, 14, 1024, 1, 1, 256, residual=True),
        gen_op_counts_qconv(1, 14, 14, 256, 1, 1, 1024),
        gen_op_counts_qconv(1, 14, 14, 256, 3, 3, 256), # 37
        gen_op_counts_qconv(1, 14, 14, 1024, 1, 1, 256, residual=True),
        gen_op_counts_qconv(1, 14, 14, 256, 1, 1, 1024),
        gen_op_counts_qconv(1, 14, 14, 256, 3, 3, 256), # 40
        gen_op_counts_qconv(1, 14, 14, 1024, 1, 1, 256, residual=True),
        gen_op_counts_qconv(1, 14, 14, 512, 1, 1, 1024),
        gen_op_counts_qconv(1, 7, 7, 512, 3, 3, 512),
        gen_op_counts_qconv(1, 7, 7, 2048, 1, 1, 1024),
        gen_op_counts_qconv(1, 7, 7, 2048, 1, 1, 512, residual=True),
        gen_op_counts_qconv(1, 7, 7, 512, 1, 1, 2048),
        gen_op_counts_qconv(1, 7, 7, 512, 3, 3, 512),   # 47
        gen_op_counts_qconv(1, 7, 7, 2048, 1, 1, 512, residual=True),
        gen_op_counts_qconv(1, 7, 7, 512, 1, 1, 2048),
        gen_op_counts_qconv(1, 7, 7, 512, 3, 3, 512),   # 50
        gen_op_counts_qconv(1, 7, 7, 2048, 1, 1, 512, residual=True),

        gen_op_counts_qconv(1, 1, 1, 1000, 1, 1, 2048),
    ]

def gen_resnet50_mem_counts(n):
    return [
        gen_mem_counts_qconv(1, 56, 56, 64, 1, 1, 64, 56, 56),
        gen_mem_counts_qconv(1, 56, 56, 64, 3, 3, 64, 56, 56),
        gen_mem_counts_qconv(1, 56, 56, 256, 1, 1, 64, 56, 56),
        gen_mem_counts_qconv(1, 56, 56, 256, 1, 1, 64, 56, 56, residual=True),
        gen_mem_counts_qconv(1, 56, 56, 64, 1, 1, 256, 56, 56),
        gen_mem_counts_qconv(1, 56, 56, 64, 3, 3, 64, 56, 56),
        gen_mem_counts_qconv(1, 56, 56, 256, 1, 1, 64, 56, 56, residual=True),
        gen_mem_counts_qconv(1, 56, 56, 64, 1, 1, 256, 56, 56),
        gen_mem_counts_qconv(1, 56, 56, 64, 3, 3, 64, 56, 56),
        gen_mem_counts_qconv(1, 56, 56, 256, 1, 1, 64, 56, 56, residual=True),
        gen_mem_counts_qconv(1, 56, 56, 128, 1, 1, 256, 56, 56),
        gen_mem_counts_qconv(1, 28, 28, 128, 3, 3, 128, 56, 56),
        gen_mem_counts_qconv(1, 28, 28, 512, 1, 1, 256, 28, 28), # 1x1 /2 by offset
        gen_mem_counts_qconv(1, 28, 28, 512, 1, 1, 128, 28, 28, residual=True),
        gen_mem_counts_qconv(1, 28, 28, 128, 1, 1, 512, 28, 28),
        gen_mem_counts_qconv(1, 28, 28, 128, 3, 3, 128, 28, 28),
        gen_mem_counts_qconv(1, 28, 28, 512, 1, 1, 128, 28, 28, residual=True),
        gen_mem_counts_qconv(1, 28, 28, 128, 1, 1, 512, 28, 28),
        gen_mem_counts_qconv(1, 28, 28, 128, 3, 3, 128, 28, 28),
        gen_mem_counts_qconv(1, 28, 28, 512, 1, 1, 128, 28, 28, residual=True),
        gen_mem_counts_qconv(1, 28, 28, 128, 1, 1, 512, 28, 28),
        gen_mem_counts_qconv(1, 28, 28, 128, 3, 3, 128, 28, 28),
        gen_mem_counts_qconv(1, 28, 28, 512, 1, 1, 128, 28, 28, residual=True),
        gen_mem_counts_qconv(1, 28, 28, 256, 1, 1, 512, 28, 28),
        gen_mem_counts_qconv(1, 14, 14, 256, 3, 3, 256, 28, 28),
        gen_mem_counts_qconv(1, 14, 14, 1024, 1, 1, 512, 14, 14), # 1x1 /2 by offset
        gen_mem_counts_qconv(1, 14, 14, 1024, 1, 1, 256, 14, 14, residual=True),
        gen_mem_counts_qconv(1, 14, 14, 256, 1, 1, 1024, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 256, 3, 3, 256, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 1024, 1, 1, 256, 14, 14, residual=True),
        gen_mem_counts_qconv(1, 14, 14, 256, 1, 1, 1024, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 256, 3, 3, 256, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 1024, 1, 1, 256, 14, 14, residual=True),
        gen_mem_counts_qconv(1, 14, 14, 256, 1, 1, 1024, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 256, 3, 3, 256, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 1024, 1, 1, 256, 14, 14, residual=True),
        gen_mem_counts_qconv(1, 14, 14, 256, 1, 1, 1024, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 256, 3, 3, 256, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 1024, 1, 1, 256, 14, 14, residual=True),
        gen_mem_counts_qconv(1, 14, 14, 256, 1, 1, 1024, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 256, 3, 3, 256, 14, 14),
        gen_mem_counts_qconv(1, 14, 14, 1024, 1, 1, 256, 14, 14, residual=True),
        gen_mem_counts_qconv(1, 14, 14, 512, 1, 1, 1024, 14, 14),
        gen_mem_counts_qconv(1, 7, 7, 512, 3, 3, 512, 14, 14),
        gen_mem_counts_qconv(1, 7, 7, 2048, 1, 1, 1024, 7, 7), # 1x1 /2 by offset
        gen_mem_counts_qconv(1, 7, 7, 2048, 1, 1, 512, 7, 7, residual=True),
        gen_mem_counts_qconv(1, 7, 7, 512, 1, 1, 2048, 7, 7),
        gen_mem_counts_qconv(1, 7, 7, 512, 3, 3, 512, 7, 7),
        gen_mem_counts_qconv(1, 7, 7, 2048, 1, 1, 512, 7, 7, residual=True),
        gen_mem_counts_qconv(1, 7, 7, 512, 1, 1, 2048, 7, 7),
        gen_mem_counts_qconv(1, 7, 7, 512, 3, 3, 512, 7, 7),
        gen_mem_counts_qconv(1, 7, 7, 2048, 1, 1, 512, 7, 7, residual=True),

        gen_mem_counts_qconv(1, 1, 1, 1000, 1, 1, 2048, 1, 1, residual=False, per_channel=True),
    ]

"""# Execution cycles of each model"""

lenet_n16_op_counts = np.array(gen_lenet5_op_counts(120))
lenet_n16_mem_counts = np.array(gen_lenet5_mem_counts(120))
lenet_n16_intensity = lenet_n16_op_counts / lenet_n16_mem_counts
lenet_n16_cycles = np.array([30182, 27060, 23925, 3628, 2106,])
lenet_x = lenet_n16_intensity
lenet_y = lenet_n16_op_counts / (lenet_n16_cycles / 0.2)

vgg11_n1_op_counts = np.array(gen_vgg11_op_counts(1))
vgg11_n1_mem_counts = np.array(gen_vgg11_mem_counts(1))
vgg11_n1_intensity = vgg11_n1_op_counts / vgg11_n1_mem_counts
vgg11_n1_cycles = np.array([117534 , 411899 , 421698 , 813618 , 413897 , 810513 , 206741 , 205536 , 8848748 , 1627222 , 407578])
vgg11_x = vgg11_n1_intensity
vgg11_y = vgg11_n1_op_counts / (vgg11_n1_cycles / 0.2)

vgg11_n32_fc_op_count = np.array([
      gen_op_counts_qconv(32, 1, 1, 4096, 1, 1, 512 * 7 * 7),
      gen_op_counts_qconv(32, 1, 1, 4096, 1, 1, 4096),
      gen_op_counts_qconv(32, 1, 1, 1000, 1, 1, 4096),
])
vgg11_n32_fc_mem_count = np.array([
      gen_mem_counts_qconv(32, 1, 1, 4096, 1, 1, 512 * 7 * 7, 1, 1, per_channel=False),
      gen_mem_counts_qconv(32, 1, 1, 4096, 1, 1, 4096, 1, 1, per_channel=False),
      gen_mem_counts_qconv(32, 1, 1, 1000, 1, 1, 4096, 1, 1, per_channel=False),
])
vgg11_n32_cycles = np.array([
    8849637 + 8850074,
    1629988 + 1630301,
    408564 + 408587,
])

vgg16_n1_op_counts = np.array(gen_vgg16_op_counts(1))
vgg16_n1_mem_counts = np.array(gen_vgg16_mem_counts(1))
vgg16_n1_intensity = vgg16_n1_op_counts / vgg16_n1_mem_counts
vgg16_n1_cycles = np.array([154921, 818710, 430385, 819874, 421206, 822828, 813532, 413407, 814722, 810092, 206638, 206602, 205536, 8848588, 1626031, 407391,])
vgg16_x = vgg16_n1_intensity
vgg16_y = vgg16_n1_op_counts / (vgg16_n1_cycles / 0.2)

vgg16_n32_fc_op_count = np.array([
      gen_op_counts_qconv(32, 1, 1, 4096, 1, 1, 512 * 7 * 7),
      gen_op_counts_qconv(32, 1, 1, 4096, 1, 1, 4096),
      gen_op_counts_qconv(32, 1, 1, 1000, 1, 1, 4096),
])
vgg16_n32_fc_mem_count = np.array([
      gen_mem_counts_qconv(32, 1, 1, 4096, 1, 1, 512 * 7 * 7, 1, 1, per_channel=False),
      gen_mem_counts_qconv(32, 1, 1, 4096, 1, 1, 4096, 1, 1, per_channel=False),
      gen_mem_counts_qconv(32, 1, 1, 1000, 1, 1, 4096, 1, 1, per_channel=False),
])
vgg16_n32_cycles = np.array([
    8850388 + 8849911,
    1628459 + 1628381,
    408756 + 408622,
])

yolo_n1_op_counts = np.array(gen_yolo_op_counts(1))
yolo_n1_mem_counts = np.array(gen_yolo_mem_counts(1))
yolo_n1_intensity = yolo_n1_op_counts / yolo_n1_mem_counts
yolo_n1_cycles = np.array([
    213799 ,
    108206 ,
    107861 ,
    105818 ,
    106830 ,
    107677 ,
    410391 ,
    811646 ,
    105870 ,
])
yolo_x = yolo_n1_intensity
yolo_y = yolo_n1_op_counts / (yolo_n1_cycles / 0.2)

resnet18_n1_op_counts = np.array(gen_resnet18_op_counts(1))
resnet18_n1_mem_counts = np.array(gen_resnet18_mem_counts(1))
resnet18_n1_intensity = resnet18_n1_op_counts / resnet18_n1_mem_counts
resnet18_n1_cycles = np.array([
    56113,
    97622,
    56163,
    98612,
    41033,
    11383,
    82950,
    55462,
    83006,
    86820,
    17889,
    66440,
    54470,
    66662,
    80838,
    20224,
    123782,
    118069,
    123777,
    45254,
])
resnet18_x = resnet18_n1_intensity
resnet18_y = resnet18_n1_op_counts / (resnet18_n1_cycles / 0.2)
resnet18_n128_fc_op_count = gen_op_counts_qconv(128, 1, 1, 1000, 1, 1, 512, residual=False)
resnet18_n128_fc_mem_count = gen_mem_counts_qconv(128, 1, 1, 1000, 1, 1, 512, 1, 1, residual=False, per_channel=False)

resnet50_n1_op_counts = np.array(gen_resnet50_op_counts(1))
resnet50_n1_mem_counts = np.array(gen_resnet50_mem_counts(1))
resnet50_n1_intensity = resnet50_n1_op_counts / resnet50_n1_mem_counts
resnet50_n64_cycles = np.array([
    904938,3558706,3397914,5883704,3560500,3560077,5879623,3610314,3558526,
    5895516,7089725,10834842,7036564,5106262,3422607,3520348,5131543,3355841,
    3522543,5101774,3423220,3520511,5129256,6711304,10532415,6761281,4241501,
    3278604,3469121,4285052,3278539,3463221,4295877,3278477,3465340,4301936,
    3277404,3464589,4241788,3328671,3470285,4284284,6471936,10168632,11483725,
    3817767,3290597,13101224,3820488,3229143,13098704,3807871,350519,
])
resnet50_n1_cycles = resnet50_n64_cycles / 64
resnet50_x = resnet50_n1_intensity
resnet50_y = resnet50_n1_op_counts / (resnet50_n1_cycles / 0.2)
resnet50_n128_fc_op_count = gen_op_counts_qconv(128, 1, 1, 1000, 1, 1, 2048, residual=False)
resnet50_n128_fc_mem_count = gen_mem_counts_qconv(128, 1, 1, 1000, 1, 1, 2048, 1, 1, residual=False, per_channel=False)

"""# (Should be calculations for GOP/s)"""

np.sum(lenet_n16_op_counts) / (np.sum(lenet_n16_cycles) / 0.2) * 2
((np.sum(vgg11_n1_op_counts[:-3]) * 32 + np.sum(vgg11_n32_fc_op_count)) / ((np.sum(vgg11_n1_cycles[:-3]) * 32 + np.sum(vgg11_n32_cycles)) / 0.2)) * 2
((np.sum(vgg16_n1_op_counts[:-3]) * 32 + np.sum(vgg16_n32_fc_op_count)) / ((np.sum(vgg16_n1_cycles[:-3]) * 32 + np.sum(vgg16_n32_cycles)) / 0.2)) * 2
np.sum(yolo_n1_op_counts) / (np.sum(yolo_n1_cycles) / 0.2) * 2
((np.sum(resnet18_n1_op_counts[:-1]) * 128 + resnet18_n128_fc_op_count) / ((np.sum(resnet18_n1_cycles[:-1]) * 128 + 89315) / 0.2)) * 2
((np.sum(resnet50_n1_op_counts[:-1]) * 128 + resnet50_n128_fc_op_count) / ((np.sum(resnet50_n1_cycles[:-1]) * 128 + 327130) / 0.2)) * 2

"""# Figure 15"""

matplotlib.rcParams.update({'font.size': 13})

fig, ax = plt.subplots(2, 3)
fig.set_figheight(8)
fig.set_figwidth(12)

dp_full = []
dp_conv = []
dp_conv_slow_pool = []
dp_conv_no_pool = []
dp_conv_res = []
dp_fc = []
dp_fc_res = []

ax[0, 0].plot(np.arange(0, 110), 6.5 * np.arange(0, 110), label='_nolegend_', linestyle='dashed')
# ax[0, 0].plot(np.arange(0, 180), 4.4 * np.arange(0, 180), label='_nolegend_', linestyle='dashed')
# ax[0, 0].plot(np.arange(0, 500), np.array([3036 * 0.2] * 500), label='_nolegend_', linestyle='dashed')
ax[0, 0].plot(np.arange(0, 500), np.array([760 * 2 * 0.2] * 500), label='_nolegend_', linestyle='dashed')
# ax[0, 0].text(2.5, 3036 * 0.2 + 20, "1518 DSPs")
ax[0, 0].text(2.5, 760 * 2 * 0.2 + 10, "760 DSPs")
dp_conv.append(ax[0, 0].scatter(lenet_x[[0, 1]], lenet_y[[0, 1]], label='5x5', c='#7f7f7f'))
dp_fc.append(ax[0, 0].scatter(lenet_x[[2, 3, 4]], lenet_y[[2, 3, 4]], label='FC', marker='s', c='#9467bd'))
dp_full.append(ax[0, 0].scatter(
    np.sum(lenet_n16_op_counts) / np.sum(lenet_n16_mem_counts),
    np.sum(lenet_n16_op_counts) / (np.sum(lenet_n16_cycles) / 0.2),
    label='Full', marker='*', s=200, c='#ff7f0e'))
ax[0, 0].set_xscale("log", base=2)
ax[0, 0].set_yscale("log", base=2)
ax[0, 0].set_title('LeNet 5')

ax[0, 1].plot(np.arange(0, 110), 6.5 * np.arange(0, 110), label='_nolegend_', linestyle='dashed')
# ax[0, 1].plot(np.arange(0, 180), 4.4 * np.arange(0, 180), label='_nolegend_', linestyle='dashed')
# ax[0, 1].plot(np.arange(0, 1000), np.array([3036 * 0.2] * 1000), label='_nolegend_', linestyle='dashed')
ax[0, 1].plot(np.arange(0, 1000), np.array([1216 * 2 * 0.2] * 1000), label='_nolegend_', linestyle='dashed')
# ax[0, 1].text(2.5, 3036 * 0.2 + 20, "1518 DSPs")
ax[0, 1].text(2.5, 1216 * 2 * 0.2 + 20, "1216 DSPs")
dp_conv.append(ax[0, 1].scatter(vgg11_x[[0]], vgg11_y[[0]], label='Shallow Pooled', c='#7f7f7f'))
dp_conv.append(ax[0, 1].scatter(vgg11_x[[1, 3, 5, 7]], vgg11_y[[1, 3, 5, 7]], label='Pooled', c='#7f7f7f'))
dp_conv_no_pool.append(ax[0, 1].scatter(vgg11_x[[2, 4, 6]], vgg11_y[[2, 4, 6]], label='No pool', marker='X', c='#8c564b'))
dp_fc.append(
    ax[0, 1].scatter(vgg11_n32_fc_op_count / vgg11_n32_fc_mem_count, vgg11_n32_fc_op_count / (vgg11_n32_cycles / 0.2), label='FC n=32', marker='s', c='#9467bd'))
dp_full.append(ax[0, 1].scatter(
    (np.sum(vgg11_n1_op_counts[:-3]) * 32 + np.sum(vgg11_n32_fc_op_count)) / (np.sum(vgg11_n1_mem_counts[:-3] * 32 + np.sum(vgg11_n32_fc_mem_count))),
    (np.sum(vgg11_n1_op_counts[:-3]) * 32 + np.sum(vgg11_n32_fc_op_count)) / ((np.sum(vgg11_n1_cycles[:-3]) * 32 + np.sum(vgg11_n32_cycles)) / 0.2),
    label='Full', marker='*', s=200, c='#ff7f0e'))
ax[0, 1].set_xscale("log", base=2)
ax[0, 1].set_yscale("log", base=2)
ax[0, 1].set_title('VGG 11')

ax[0, 2].plot(np.arange(0, 110), 6.5 * np.arange(0, 110), label='_nolegend_', linestyle='dashed')
# ax[0, 2].plot(np.arange(0, 180), 4.4 * np.arange(0, 180), label='_nolegend_', linestyle='dashed')
# ax[0, 2].plot(np.arange(0, 1000), np.array([3036 * 0.2] * 1000), label='_nolegend_', linestyle='dashed')
ax[0, 2].plot(np.arange(0, 1000), np.array([1216 * 2 * 0.2] * 1000), label='_nolegend_', linestyle='dashed')
# ax[0, 2].text(2.5, 3036 * 0.2 + 20, "1518 DSPs")
ax[0, 2].text(2.5, 1216 * 2 * 0.2 + 20, "1216 DSPs")
dp_conv.append(ax[0, 2].scatter(vgg16_x[[0]], vgg16_y[[0]], label='Shallow', c='#7f7f7f'))
dp_conv.append(ax[0, 2].scatter(vgg16_x[[1, 3, 6, 9, 12]], vgg16_y[[1, 3, 6, 9, 12]], label='Pooled', c='#7f7f7f'))
dp_conv_no_pool.append(ax[0, 2].scatter(vgg16_x[[2, 4, 5, 7, 8, 10, 11]], vgg16_y[[2, 4, 5, 7, 8, 10, 11]], label='No pool', marker='X', c='#8c564b'))
dp_fc.append(
    ax[0, 2].scatter(vgg16_n32_fc_op_count / vgg16_n32_fc_mem_count, vgg16_n32_fc_op_count / (vgg16_n32_cycles / 0.2), label='FC', marker='s', c='#9467bd'))
dp_full.append(ax[0, 2].scatter(
    (np.sum(vgg16_n1_op_counts[:-3]) * 32 + np.sum(vgg16_n32_fc_op_count)) / (np.sum(vgg16_n1_mem_counts[:-3] * 32 + np.sum(vgg16_n32_fc_mem_count))),
    (np.sum(vgg16_n1_op_counts[:-3]) * 32 + np.sum(vgg16_n32_fc_op_count)) / ((np.sum(vgg16_n1_cycles[:-3]) * 32 + np.sum(vgg16_n32_cycles)) / 0.2),
    label='Full', marker='*', s=200, c='#ff7f0e'))
ax[0, 2].set_xscale("log", base=2)
ax[0, 2].set_yscale("log", base=2)
ax[0, 2].set_title('VGG 16')

ax[1, 0].plot(np.arange(0, 110), 6.5 * np.arange(0, 110), label='_nolegend_', linestyle='dashed')
# ax[1, 0].plot(np.arange(0, 180), 4.4 * np.arange(0, 180), label='_nolegend_', linestyle='dashed')
# ax[1, 0].plot(np.arange(0, 1000), np.array([3036 * 0.2] * 1000), label='_nolegend_', linestyle='dashed')
ax[1, 0].plot(np.arange(0, 1000), np.array([1216 * 2 * 0.2] * 1000), label='_nolegend_', linestyle='dashed')
# ax[1, 0].text(2.5, 3036 * 0.2 + 20, "1518 DSPs")
ax[1, 0].text(2.5, 1216 * 2 * 0.2 + 20, "1216 DSPs")
dp_conv.append(ax[1, 0].scatter(yolo_x[0], yolo_y[0], label='Shallow 3 pool', c='#7f7f7f'))
dp_conv.append(ax[1, 0].scatter(yolo_x[1], yolo_y[1], label='Shallow 16 pool', c='#7f7f7f'))
dp_conv.append(ax[1, 0].scatter(yolo_x[2], yolo_y[2], label='Shallow 32 pool', c='#7f7f7f'))
dp_conv.append(ax[1, 0].scatter(yolo_x[[3, 4]], yolo_y[[3, 4]], label='Deep pool', c='#7f7f7f'))
dp_conv_slow_pool.append(ax[1, 0].scatter(yolo_x[5], yolo_y[5], label='Deep slow pool', marker='D', c= '#bcbd22'))
dp_conv.append(ax[1, 0].scatter(yolo_x[[6, 7]], yolo_y[[6, 7]], label='Deep', c='#7f7f7f'))
dp_fc.append(ax[1, 0].scatter(yolo_x[8], yolo_y[8], label='1x1', marker='s', c='#9467bd'))
dp_full.append(ax[1, 0].scatter(
    np.sum(yolo_n1_op_counts) / np.sum(yolo_n1_mem_counts),
    np.sum(yolo_n1_op_counts) / (np.sum(yolo_n1_cycles) / 0.2),
    label='Full n=1', marker='*', s=200, c='#ff7f0e'))
ax[1, 0].set_xscale("log", base=2)
ax[1, 0].set_yscale("log", base=2)
ax[1, 0].set_title('Tiny YOLOv2')

ind_3x3 = [0, 2, 7, 12, 17]
ind_3x3_residual = [1, 3, 6, 8, 11, 13, 16, 18]
ind_3x3_stride2 = [4, 9, 14]
ind_1x1 = [19]
ind_1x1_stride2 = [5, 10, 15]
ax[1, 1].plot(np.arange(0, 110)[8:], (6.5 * np.arange(0, 110))[8:], label='_nolegend_', linestyle='dashed')
# ax[1, 1].plot(np.arange(0, 180)[8:], (4.4 * np.arange(0, 180))[8:], label='_nolegend_', linestyle='dashed')
# ax[1, 1].plot(np.arange(0, 500)[8:], (np.array([3036 * 0.2] * 500))[8:], label='_nolegend_', linestyle='dashed')
ax[1, 1].plot(np.arange(0, 500)[8:], (np.array([1260 * 2 * 0.2] * 500))[8:], label='_nolegend_', linestyle='dashed')
# ax[1, 1].text(15.5, 3036 * 0.2 + 20, "1518 DSPs")
ax[1, 1].text(15.5, 1260 * 2 * 0.2 + 20, "1260 DSPs")
dp_conv_no_pool.append(ax[1, 1].scatter(resnet18_x[ind_3x3], resnet18_y[ind_3x3], label='3x3', marker='X', c='#8c564b'))
dp_fc.append(ax[1, 1].scatter(resnet18_x[ind_1x1_stride2], resnet18_y[ind_1x1_stride2], label='1x1 /2', marker='s', c='#9467bd'))
dp_conv_no_pool.append(ax[1, 1].scatter(resnet18_x[ind_3x3_stride2], resnet18_y[ind_3x3_stride2], label='3x3 /2', marker='X', c='#8c564b'))
dp_conv_res.append(ax[1, 1].scatter(resnet18_x[ind_3x3_residual], resnet18_y[ind_3x3_residual], label='3x3 + residual', marker='+', c='#e377c2'))
dp_fc.append(ax[1, 1].scatter(
    resnet18_n128_fc_op_count / resnet18_n128_fc_mem_count, resnet18_n128_fc_op_count / (89315 / 0.2), label='FC', marker='s', c='#9467bd'))
dp_full.append(ax[1, 1].scatter(
    (np.sum(resnet18_n1_op_counts[:-1]) * 128 + resnet18_n128_fc_op_count) / (np.sum(resnet18_n1_mem_counts[:-1]) * 128 + resnet18_n128_fc_mem_count),
    (np.sum(resnet18_n1_op_counts[:-1]) * 128 + resnet18_n128_fc_op_count) / ((np.sum(resnet18_n1_cycles[:-1]) * 128 + 89315) / 0.2),
    label='Full', marker='*', s=200, c='#ff7f0e'
))
ax[1, 1].set_xscale("log", base=2)
ax[1, 1].set_yscale("log", base=2)
ax[1, 1].set_title('ResNet 18')

ind_1x1 = [0, 2, 4, 7, 10, 14, 17, 20, 23, 27, 30, 33, 36, 39, 42, 46, 49]
ind_1x1_stride2 = [12, 25, 44]
ind_1x1_residual = [3, 6, 9, 13, 16, 19, 22, 26, 29, 32, 35, 38, 41, 45, 48, 51]
ind_3x3 = [1, 5, 8, 15, 18, 21, 28, 31, 34, 37, 40, 47, 50]
ind_3x3_stride2 = [11, 24, 43]
ax[1, 2].plot(np.arange(0, 110)[8:], (6.5 * np.arange(0, 110))[8:], label='_nolegend_', linestyle='dashed')
# ax[1, 2].plot(np.arange(0, 180)[8:], (4.4 * np.arange(0, 180))[8:], label='_nolegend_', linestyle='dashed')
# ax[1, 2].plot(np.arange(0, 500)[8:], (np.array([3036 * 0.2] * 500))[8:], label='_nolegend_', linestyle='dashed')
ax[1, 2].plot(np.arange(0, 500)[8:], (np.array([1260 * 2 * 0.2] * 500))[8:], label='_nolegend_', linestyle='dashed')
# ax[1, 2].text(15.5, 3036 * 0.2 + 20, "1518 DSPs")
ax[1, 2].text(15.5, 1260 * 2 * 0.2 + 20, "1260 DSPs")
dp_fc.append(ax[1, 2].scatter(resnet50_x[ind_1x1], resnet50_y[ind_1x1], label='1x1', marker='s', c='#9467bd'))
dp_conv_no_pool.append(ax[1, 2].scatter(resnet50_x[ind_3x3], resnet50_y[ind_3x3], label='3x3', marker='X', c='#8c564b'))
dp_fc.append(ax[1, 2].scatter(resnet50_x[ind_1x1_stride2], resnet50_y[ind_1x1_stride2], label='1x1 /2', marker='s', c='#9467bd'))
dp_conv_no_pool.append(ax[1, 2].scatter(resnet50_x[ind_3x3_stride2], resnet50_y[ind_3x3_stride2], label='3x3 /2', marker='x', c='#d62728'))
dp_fc_res.append(ax[1, 2].scatter(resnet50_x[ind_1x1_residual], resnet50_y[ind_1x1_residual], label='1x1 + residual', marker='P', c='#2ca02c'))
dp_fc.append(ax[1, 2].scatter(
    resnet50_n128_fc_op_count / resnet50_n128_fc_mem_count, resnet50_n128_fc_op_count / (327130 / 0.2), label='FC', marker='s', c='#9467bd'))
dp_full.append(ax[1, 2].scatter(
    (np.sum(resnet50_n1_op_counts[:-1]) * 128 + resnet50_n128_fc_op_count) / (np.sum(resnet50_n1_mem_counts[:-1]) * 128 + resnet50_n128_fc_mem_count),
    (np.sum(resnet50_n1_op_counts[:-1]) * 128 + resnet50_n128_fc_op_count) / ((np.sum(resnet50_n1_cycles[:-1]) * 128 + 327130) / 0.2),
    label='Full', marker='*', s=200, c='#ff7f0e'))
ax[1, 2].set_xscale("log", base=2)
ax[1, 2].set_yscale("log", base=2)
ax[1, 2].set_title('ResNet 50')

for q in ax:
  for w in q:
    w.set_ylabel('GOp/s')
    break
for q in ax[-1, :]:
  q.set_xlabel('Op/byte')

fig.legend([tuple(dp_full), tuple(dp_conv_no_pool), tuple(dp_conv), tuple(dp_conv_slow_pool), tuple(dp_conv_res), tuple(dp_fc), tuple(dp_fc_res)],
           ["Full model", "Conv2D", "Conv2D + Pool", "Conv2D + Stride 1 Pool", "Conv2D + Residual",
            "FC", "FC + Residual"], ncol=4, loc='upper center')
save_path = os.path.join(RESULTS_DIR, 'rooflines.pdf')
plt.savefig(save_path)

"""# Figure 16"""

def foo():
    import pandas as pd
    import matplotlib
    import matplotlib.pyplot as plt
    import numpy as np
    from matplotlib.pyplot import figure

    fpga_vgg16_conv = np.array([154921, 818710, 430385, 819874, 421206, 822828, 813532, 413407, 814722, 810092, 206638, 206602, 205536,]) * 32 / 0.2 # N = 1 to N = 32
    fpga_vgg16_fc   = np.array([8850388 + 8849911, 1628459 + 1628381, 408756 + 408622]) / 0.2
    fpga_vgg16      = np.concat([fpga_vgg16_conv, fpga_vgg16_fc])

    roofline_vgg16_mem_counts = np.array([
        107636736, 129634304, 79437824, 366223360, 189546496, 353386496, 334118912, 170295296, 327712768, 318078976, 81952768, 81952768, 79544320, 103698433, 17043457, 4260073
    ])
    roofline_vgg16_op_counts = np.array([
        2877292544, 59292778496, 29646389248, 59241398272, 29620699136, 59215708160, 59215708160, 29607854080, 59202863104, 59202863104, 14800715776, 14800715776, 14800715776, 3288465408, 537001984, 131104000
    ])
    roofline_vgg16 = np.array([
        1.65594978e+07, 1.21901272e+08, 6.09506358e+07, 1.21795638e+08, 6.08978189e+07, 1.21742821e+08, 1.21742821e+08, 6.08714105e+07, 1.21716413e+08, 1.21716413e+08, 3.04291032e+07, 3.04291032e+07, 3.04291032e+07, 1.59536051e+07, 2.62207031e+06, 6.55395846e+05
    ])

    theory_vgg16_eff = np.array([
        0.408,
        1.0,

        1.0,
        1.0,

        1.0,
        1.0,
        1.0,

        1.0,
        1.0,
        1.0,

        1.0,
        1.0,
        1.0,

        0.077,
        0.069,
        0.067,
    ])
    theory_vgg16 = np.maximum(1 / 6.5 * roofline_vgg16_mem_counts, 1 / (1216 * 2 * 0.2 * theory_vgg16_eff) * roofline_vgg16_op_counts)

    plt.figure(figsize=(8, 2))
    layers = len(fpga_vgg16)
    iota = np.arange(layers) * 1.4
    plt.bar(iota - 0.1, fpga_vgg16 / 1_000_000, 0.25, label='Real', color='#f5b935', edgecolor='black')
    plt.bar(iota + 0.25, theory_vgg16 / 1_000_000, 0.25, label='Theory', color='#4bac35', edgecolor='black')
    plt.bar(iota + 0.6, roofline_vgg16 / 1_000_000, 0.25, label='Roofline', color='#3778c2', edgecolor='black')
    plt.xticks(iota + 0.25, [f"{i + 1}" for i in range(layers)])
    plt.ylabel('Runtime (ms)')
    plt.xlabel('Layer')
    # plt.title('VGG 16')
    # plt.yscale("log", base=2)
    plt.legend()
    pass
    save_path = os.path.join(RESULTS_DIR, 'vgg16_runtime.pdf')
    plt.savefig(save_path)
    plt.savefig(save_path, bbox_inches="tight")
    plt.show()

foo()

def recursive_chmod(path, mode):
    for root, dirs, files in os.walk(path):
        for d in dirs:
            os.chmod(os.path.join(root, d), mode)
        for f in files:
            os.chmod(os.path.join(root, f), mode)
    os.chmod(path, mode)

recursive_chmod(RESULTS_DIR, 0o777)