-- floating_point_dsp.vhd

-- Generated using ACDS version 17.1.1 273

library IEEE;
library altera_fpdsp_block_171;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity floating_point_dsp is
	port (
		aclr   : in  std_logic                     := '0';             --   aclr.aclr
		ay     : in  std_logic_vector(31 downto 0) := (others => '0'); --     ay.ay
		az     : in  std_logic_vector(31 downto 0) := (others => '0'); --     az.az
		clk    : in  std_logic                     := '0';             --    clk.clk
		ena    : in  std_logic                     := '0';             --    ena.ena
		result : out std_logic_vector(31 downto 0)                     -- result.result
	);
end entity floating_point_dsp;

architecture rtl of floating_point_dsp is
	component floating_point_dsp_altera_fpdsp_block_171_5y5du3y_cmp is
		port (
			clk    : in  std_logic                     := 'X';             -- clk
			ena    : in  std_logic                     := 'X';             -- ena
			aclr   : in  std_logic                     := 'X';             -- aclr
			result : out std_logic_vector(31 downto 0);                    -- result
			ay     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- ay
			az     : in  std_logic_vector(31 downto 0) := (others => 'X')  -- az
		);
	end component floating_point_dsp_altera_fpdsp_block_171_5y5du3y_cmp;

	for fpdsp_block_0 : floating_point_dsp_altera_fpdsp_block_171_5y5du3y_cmp
		use entity altera_fpdsp_block_171.floating_point_dsp_altera_fpdsp_block_171_5y5du3y;
begin

	fpdsp_block_0 : component floating_point_dsp_altera_fpdsp_block_171_5y5du3y_cmp
		port map (
			clk    => clk,    --    clk.clk
			ena    => ena,    --    ena.ena
			aclr   => aclr,   --   aclr.aclr
			result => result, -- result.result
			ay     => ay,     --     ay.ay
			az     => az      --     az.az
		);

end architecture rtl; -- of floating_point_dsp
